USE [MSS]
GO

/****** Object:  Table [dbo].[Crud]    Script Date: 13-07-2023 23:25:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Crud](
	[CrudId] [uniqueidentifier] NOT NULL,
	[CrudName] [varchar](6) NOT NULL,
 CONSTRAINT [PK_Crud] PRIMARY KEY CLUSTERED 
(
	[CrudId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


