USE [MSS]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER FUNCTION [dbo].[GetSAdminName]()
RETURNS INT
AS
BEGIN
	DECLARE @SARoleName VARCHAR(50) = 'SAdmin';
    
    RETURN @SARoleName;
END;
